03 Feb, 2026 LAB 2

In [ ]:
#math kernel library for intel

In [1]:
import numpy as np

1. Create a function to check whether numpy array has Zero values or not.

In [ ]:
def check_zero(a):
    for x in a:
        if(x == 0):
            return False     
    return True

a = np.array([1,2,3,4,5,0,0,4])
print(check_zero(a))


False


2. Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [ ]:
marks = np.array([20, 35, 44, 70, 89, 90, 78, 88, 67, 67])
print("=== given marks ===")
print(marks)

print("\n=== filtered marks ===")
passed = np.array([int(x) for x in marks if int(x) >= 40])
# passed = marks[marks>=40]
print("Type:", passed.dtype, "\nShape:", passed.shape, "\nData structure:", type(passed))
print(passed)

=== given marks ===
[20 35 44 70 89 90 78 88 67 67]

=== filtered marks ===
Type: int64 
Shape: (8,) 
Data structure: <class 'numpy.ndarray'>
[44 70 89 90 78 88 67 67]


In [ ]:
print("Median: ", np.median(passed))
print("Mean: ",np.mean(passed))

Median:  74.0
Mean:  74.125


3. Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [50]:
dob = {}
ch = 'y'
count = 1
while ch == 'y':
    date = input("Enter DOB (YYYY-MM-DD)")
    year = (np.datetime64("now", 'Y')) - (np.datetime64(date,'Y'))
    if year == 18:
        dob[f"Student {count}"] = (18, "First")
    elif year == 19:
        dob[f"Student {count}"] = (19, "Second")
    elif year == 20:
        dob[f"Student {count}"] = (20, "Third")
    elif year == 21:
        dob[f"Student {count}"] = (21, "Fourth")
    else:
        raise Exception("Age is either > 21 or < 18")
    count += 1
        
    ch = input("Do you want to enter more y/n?")

print(dob)


{'Student 1': (21, 'Fourth'), 'Student 2': (20, 'Third'), 'Student 3': (19, 'Second'), 'Student 4': (18, 'First')}


In [51]:
for key in dob:
    print(key, ": ", dob[key])

Student 1 :  (21, 'Fourth')
Student 2 :  (20, 'Third')
Student 3 :  (19, 'Second')
Student 4 :  (18, 'First')


4. Create a function to sort 2d Array by a column.

In [77]:
def sortBycol(arr, col):
    arr1 = arr[np.argsort((arr[:, col]), axis=0)]
    return arr1

arr = np.array([[10,20,30],[11,22,65],[7, 47, 34], [88, 23, 13]])
col = (int)(input("Enter column index to sort (0-indexed)"))
print(arr, "\n")

print(f"\n=== sorted as per column {col} ===")
print (sortBycol(arr,col))

[[10 20 30]
 [11 22 65]
 [ 7 47 34]
 [88 23 13]] 


=== sorted as per column 2 ===
[[88 23 13]
 [10 20 30]
 [ 7 47 34]
 [11 22 65]]
