3 Feb, 2026 LAB 2

In [2]:
import numpy as np

1. Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be
   array([[ 0.,  1.,  0.],
             [ 0.,  0.,  1.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
            [ 1.,  0.,  0.]])

In [ ]:
def hot_encoding(arr):
    len = np.max(arr)
    list = []
    for index in arr:
        temp_arr = np.zeros(len)
        temp_arr[index - 1] = 1
        list.append(temp_arr)

    list = np.asarray(list)
    return list


arr = np.array([2,3,2,2,2,1])
print(hot_encoding(arr))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


2. Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [ ]:
def drop_nan(arr):
    idx = np.where(np.isnan(arr))
    return np.delete(arr,idx)
        
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr = drop_nan(arr)
print(arr)

[1. 2. 3. 5. 6. 7.]


3. Find Index of Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [24]:
def loc_maxima(arr):
    grad = np.array([])
    for i in range(len(arr) - 1):  # or grad = np.diff(arr)
        grad = np.append(grad, arr[i+1] - arr[i])
        
    return np.where(grad < 0)


a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
idx = np.array(loc_maxima(a))
print(idx)

[[2 5]]


4. From the given 1d array arr, generate a 2d matrix using strides,
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
w and s will be provided by user
Calculate the moving average.

In [ ]:
def moving_avg(arr, beta=0.5):
    movAvg = arr[0]

    for x in arr[1:]:
        movAvg = (beta * movAvg) + (1 - beta) * x

    return movAvg

def onedTo2d(arr, w, s):
    windows = []
    avg_arr = np.array([])
    start = 0
    while(start + w) < len(arr):
        temp_arr = arr[start : start + w]
        windows.append(temp_arr)
        avg_arr = np.append(avg_arr, np.average(temp_arr))
        start += s

    if(start < len(arr)):
        temp_arr = arr[start : start + w] 
        temp_arr = np.concatenate((temp_arr, np.zeros(w - len(temp_arr), dtype=temp_arr.dtype))) #padding of 0

    windows.append(temp_arr)
    avg_arr = np.append(avg_arr, np.average(temp_arr))


    return np.asarray(windows), moving_avg(avg_arr)

In [49]:
arr =  np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

w = (int)(input("Enter window size"))
s = (int)(input("Enter stride value"))

mat, mv_avg = onedTo2d(arr, w, s)

print(mat)
print(f"Moving average of above matrix: {mv_avg}")


[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14  0]]
Moving average of above matrix: 9.65625
